name: Daily Weather Bot
on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 실행 (UTC 기준, 상관없음)
jobs:
  get-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Check Weather
        run: curl wttr.in/Seoul
